name: Report an issue
description: If you expereince something unexpected, please create a report to help us improve Ockam.
body:
  - type: input
    attributes:
      label: Ockam Version
      description: Please tell us the version of Ockam Command or Library that you’re using.
      placeholder: 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: A clear and concise description of what you observed is.
      placeholder: |
        1. Run '...'
        2. Then run '...'
        3. Then see the following error '...'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed behavior
      description: A clear and concise description of what you observed is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear description.
    validations:
      required: true
