name: Request a new feature
description: Request a new feature or enhancement to Ockam
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear description.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Desired Behavior
      description: A clear description.
    validations:
      required: true
